name: build
on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Build & Test
        run: make build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --snapshot --skip-publish --rm-dist
