name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u slamdev --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
